version: 1.0.{build}
image: Visual Studio 2017
before_build:
- ps: nuget restore
build:
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: xKi5tQ2ED3G/9Hc6OCxJpRyEp7GZMHBl1twwyUx8Qhmkrr6+4nOI4EE17q9FC+ub
  skip_symbols: true
  artifact: /.*\.nupkg/